name: Publish to PyPI Test

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ development ]  # Or whatever branch you want to trigger from

jobs:
  build-and-publish:
    name: Build and Publish to PyPI Test
    runs-on: ubuntu-latest
    environment: freeipaconsistencycheck-pypi-test
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -y libsasl2-dev libldap2-dev libssl-dev libkrb5-dev gcc
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build setuptools wheel twine
    
    - name: Build package
      run: |
        python -m build
    
    - name: Get version
      id: get_version
      run: |
        VERSION=$(python -c "import os; import sys; sys.path.insert(0, os.path.abspath('src')); from freeipaconsistencycheck import __version__; print(__version__)")
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    
    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_TEST_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true
        verbose: true